/** Define ids for each page. */
export const PAGE_IDS = {
  ABOUT_US: 'about-us',
  ADMIN_PAGE: 'admin-page',
  CREATE_ORGANIZATION: 'create-organization',
  VOLUNTEER_PROFILE: 'volunteer-profile',
  LANDING: 'landing',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  ORGANIZATION_PAGE: 'organization-page',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  VOLUNTEER_SETTINGS: 'volunteer-settings',
  ADD_EVENT: 'add-event',
  LIST_EVENTS: 'listEvents',
  FEEDBACK: 'feedback',
  DASHBOARD_VOLUNTEER: 'dashboard-volunteer',
  EDIT_EVENT: 'edit-event',
  VOLUNTEER_EVENT_PAGE: 'volunteer-event-page',
  SEND_NOTIFCATIONS: 'send-notifications',
  START_ORGANIZATION: 'start-organization',
};
