/** Define ids for each page. */
export const PAGE_IDS = {
  ABOUT_US: 'about-us',
  ADD_STUFF: 'add-stuff',
  ADMIN_PAGE: 'admin-page',
  EDIT_STUFF: 'edit-stuff',
  VOLUNTEER_PROFILE: 'volunteer-profile',
  LANDING: 'landing',
  LIST_STUFF: 'list-stuff',
  LIST_STUFF_ADMIN: 'list-stuff-admin',
  LIST_STUFF_VOLUNTEER: 'list-stuff-volunteer',
  MANAGE_DATABASE: 'manage-database',
  NOT_AUTHORIZED: 'not-authorized',
  NOT_FOUND: 'not-found',
  ORGANIZATION_PAGE: 'organization-page',
  SIGN_IN: 'sign-in',
  SIGN_OUT: 'sign-out',
  SIGN_UP: 'sign-up',
  VOLUNTEER_SETTINGS: 'volunteer-settings',
  ADD_EVENT: 'add-event',
  LIST_EVENTS: 'listEvents',
  FEEDBACK: 'feedback',
  DASHBOARD_VOLUNTEER: 'dashboard-volunteer',
  EDIT_EVENT: 'edit-event',
  VOLUNTEER_EVENT_PAGE: 'volunteer-event-page',

};
